# Generated by Django 4.2.3 on 2023-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_knowledge_tag_sitting_user_answers_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='knowledge_tag',
            field=models.CharField(max_length=100, verbose_name='知識點'),
        ),
    ]
