# Generated by Django 4.2.3 on 2023-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_knowledge_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge_tag1',
            field=models.CharField(default='', max_length=100, verbose_name='知識點'),
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge_tag2',
            field=models.CharField(default='', max_length=100, verbose_name='知識點'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_tag',
            field=models.CharField(default='', max_length=100, verbose_name='知識點'),
        ),
    ]
