# Generated by Django 4.2.3 on 2023-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_knowledge_tag1_question_knowledge_tag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='knowledge_tag',
            field=models.CharField(default='', max_length=100, verbose_name='知識點1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_tag1',
            field=models.CharField(default='', max_length=100, verbose_name='知識點2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_tag2',
            field=models.CharField(default='', max_length=100, verbose_name='知識點3'),
        ),
    ]
