# Generated by Django 4.2.3 on 2023-08-27 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_alter_question_knowledge_tag1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': '使用者進度', 'verbose_name_plural': '使用者進度記錄'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(blank=True, default=False, help_text='如果是，則測驗不會在測驗列表中顯示，只能由可以編輯測驗的使用者進行。', verbose_name='草稿'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text='如果是，則每個使用者的每次嘗試的結果將被存儲。需要打分。', verbose_name='考試卷'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=False, help_text='如果是，則只允許使用者嘗試一次。', verbose_name='單次嘗試'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_answers',
            field=models.TextField(blank=True, default='{}', verbose_name='使用者答案'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_answers_correct',
            field=models.TextField(blank=True, default='{}', verbose_name='使用者答案是否正確'),
        ),
    ]
