# Generated by Django 4.2.3 on 2023-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_progress_options_alter_progress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitting',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
    ]
