# Generated by Django 4.2.3 on 2023-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dep_head',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachloar', '學士學位'), ('Master', '碩士學位')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
